### ISSUE TITLE
Subscription Entrypoint

### ISSUE THREAD

**Issue by john-rubin** [graphql-dotnet/conventions#91]
Hello,

When querying on a Subscription, the Subscription entry point is never invoked, unlike Query/Mutation entry points.  Is this known behavior? (version 1.4.0)

Given a query:
`subscription testSubscription {
  testModel {
    id
  }
}`

And an entry point:
`	
    [ImplementViewer(OperationType.Subscription)]
    public class Subscription
    {
		public Task<TestModel> TestModel()
		{
			return Task.FromResult(new TestModel());
		}
    }`

The TestModel function is not invoked, and the data result is always null.  I was planning on setting up continued delivery to the requester, originating from this entry point, but I'm either doing something wrong, or this isn't implemented just yet.

I know that subscription behavior does not intend to have a return result until an update occurs on the requested model, but I would have expected the subscription entry point to be hit.

Appreciate your help.

Thanks,
John

**Comment by tlil** [comment]
Hi John,

The short answer is that with the subscription changes that were introduced in graphql-dotnet in February, the subscription part of the Conventions library is no longer 100% workable. Apologies for it not being in there already - I'll take an action to update that.

See for instance the tests introduced in the underlying engine for more info on how it is supposed to work: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Subscription/SubscriptionTests.cs

I will need to expose part of this API so that you can implement subscriptions properly from within Conventions as well. @rodolfotorres said that he'd be interested in taking this work on actually: https://github.com/graphql-dotnet/conventions/issues/89.

Will keep you posted on progress.

Cheers,
Tommy

**Comment by tlil** [comment]
I'll close this as a dup of #89

**Comment by awarenet** [comment]
Hi @tlil 
Any update on when subs might be available in conventions?
Cheers

**Comment by tlil** [comment]
@awarenet see https://github.com/graphql-dotnet/conventions/issues/89

Due to lack of responsiveness there, I was gonna pick it up in the next week or so. So hopefully not too long.
