### ISSUE TITLE
Subclasses in queries returning error

### ISSUE THREAD

**Issue by jordisan** [graphql-dotnet/conventions#93]
Hi;
when trying to query for a field which is returning a subclass of the declared class, I get an error similar to this:
"Expected value of type \"GraphQL.Conventions.Adapters.Types.OutputObjectGraphType`1[Superclass]\" but got: Subclass."

Is there any way to make it work? Thanks.

**Comment by tlil** [comment]
Can you post a snippet of the type definitions please?

**Comment by jordisan** [comment]
Let me try (we are trying to expose through GraphQL an existing library which is already quite complex).

This is the query class:
```
    [ImplementViewer(OperationType.Query)]
    public class Query
    {
        private Server _server;

        public Query(Server server)
        {
            _server = server;
        }

        [Description("Service for a single type of transactions")]
        public Service service(
            TransactionTypes serviceType,
            string language, 
            string version, 
            string email, 
            string password
        ) {
            return _server.GetService(
                serviceType,
                language,
                version,
                email,
                password
            );
        }
    }

```
`_server.GetService(...)` doesn't return a `Service` object, but an object which is `HotelServiceAvail`, a subclass of `Service`; so, when I try to query like this:
```
query {
  service(...) 
}
```
I get that error `Expected value of type \"GraphQL.Conventions.Adapters.Types.OutputObjectGraphType´1[Service]\" but got: HotelServiceAvail.`

**Comment by BernMcCarty** [comment]
For what it is worth, I have exactly the same error and scenario and question as jordisan.  There should be some means of informing the framework about additional .NET types that come into the equation only via polymorphism; types that the system otherwise cannot even see merely by reflecting on my query type. Does such a mechanism exist?  If not, then I cannot expose a polymorphic object through my query without getting this error.

Something analogous to the mongo c# driver's [BsonKnownTypes attribute or it's RegistgerClassMap call](http://mongodb.github.io/mongo-csharp-driver/2.0/reference/bson/mapping/polymorphism/#specifying-known-types).

**Comment by tlil** [comment]
Take a look at `AddPossibleType()` in `GraphTypeInfo.cs` and `GetType()` in `ObjectReflector.cs`. You could try play around with those. At the moment, the library is only looking at interfaces and their available 'implementations'.

**Comment by tlil** [comment]
I'll close this for now - but feel free to re-open if you are still struggling with this. In short, the library is expecting `Service` to be an interface, not a base class (to try to be consistent with GraphQL).
